### ISSUE TITLE
(updated on newest version) Now i get Error while parsing the resource: de

### ISSUE THREAD

**Issue by innc** [akoenig/express-lingua#20]
Hello :)
I updated on newest express-lingua version, but now i get this error and i havent changed something at de.json file and other language files....

Exception at function appConfig.main: Error: Lingua: Error while parsing the resource: de
Error: Lingua: Error while parsing the resource: de
    at /myDirectory/node_modules/lingua/lib/guru.js:80:31
    at Array.forEach (native)
    at new module.exports.Guru (/myDirectory/node_modules/lingua/lib/guru.js:63:15)
    at module.exports (/myDirectory/node_modules/lingua/lib/lingua.js:70:12)
    at Function.<anonymous> (/myDirectory/modules/appConfig.js:28:25)
    at Function.app.configure (/myDirectory/node_modules/express/lib/application.js:396:61)
    at Object.appConfig.main (/myDirectory/modules/appConfig.js:14:17)
    at Object.webInfSys.main (/myDirectory/js/server/webInfSys.js:50:23)
    at Object.<anonymous> (/myDirectory/js/server/webInfSys.js:77:11)
    at Module._compile (module.js:449:26)

My file look like this:
{
    "home":
    {
 "MySQLHttpServer": "v",
 "AirportViennaAndAustroControl": "b",
 "DatabaseMapView": "a"
    }
}

**Comment by akoenig** [comment]
Hey,

thanks for reporting this problem. I published a new release (0.3.6) just a few seconds ago. Extended the stacktrace a little bit. Could you update to this version and post the stacktrace again? Thanks :)

/André

**Comment by innc** [comment]
I updated on version 0.3.6. Now I get the this error message:
(like i said, all working fine before i updated from 0.3.4 on 0.3.5 and today on 0.3.6,
i hope my info will help you)

Exception at function appConfig.main: Error: Lingua: Error while parsing the resource: de - Error: Cannot find module 'i18n/de.json'
Error: Lingua: Error while parsing the resource: de - Error: Cannot find module 'i18n/de.json'
    at /myDirectory/node_modules/lingua/lib/guru.js:80:31
    at Array.forEach (native)
    at new module.exports.Guru (/myDirectory/node_modules/lingua/lib/guru.js:63:15)
    at module.exports (/myDirectory/node_modules/lingua/lib/lingua.js:70:12)
    at Function.<anonymous> (/myDirectory/modules/appConfig.js:28:25)
    at Function.app.configure (/myDirectory/node_modules/express/lib/application.js:395:61)
    at Object.appConfig.main (/myDirectory/modules/appConfig.js:14:17)
    at Object.webInfSys.main (/myDirectory/js/server/webInfSys.js:50:23)
    at Object.<anonymous> (/myDirectory/js/server/webInfSys.js:77:11)
    at Module._compile (module.js:449:26)

My code snippet:
app.configure(function()
{
.....
var lingua = require('lingua');
app.use(lingua(app,
{
defaultLocale: 'en',
path: 'i18n',
storageKey: 'lang'
}));
.....
});
